# Dify Helm Chart Definition File
# This file defines the basic information and dependencies of the Helm Chart
#
# Version Information:
# - version: Chart version number, following Semantic Versioning
# - appVersion: Dify application version number
#
# Dependencies Description:
# - redis: Used for caching and message queue
# - postgresql: Main database
# - minio: Object storage service
# - weaviate: Vector database option
# - qdrant: Vector database option
#
# Notes:
# 1. Version numbers should follow Semantic Versioning
# 2. Dependencies versions should be compatible with Dify version
# 3. It's recommended to use stable versions of dependencies

apiVersion: v2
name: dify
description: A Helm chart for Dify

home: https://github.com/langgenius/dify

maintainers:
  - name: Ruiruiz
    email: ruriuiz@gmail.com
    url: https://github.com/Ruiruiz30

type: application

version: 0.1.0

appVersion: "1.4.1"

dependencies:
  - name: redis
    version: "18.1.2"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  - name: postgresql
    version: "12.1.6"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  - name: minio
    version: "12.8.7"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
  - name: weaviate
    version: "16.3.0"
    repository: "https://weaviate.github.io/weaviate-helm"
  - name: qdrant
    version: "0.7.0"
    repository: "https://qdrant.github.io/qdrant-helm"
