 {{- if .Values.plugin_daemon.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dify.fullname" . }}-plugin-storage
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
spec:
  accessModes:
    - {{ .Values.plugin_daemon.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.plugin_daemon.persistence.size | default "10Gi" }}
  {{- if .Values.plugin_daemon.persistence.storageClass }}
  storageClassName: {{ .Values.plugin_daemon.persistence.storageClass }}
  {{- end }}
{{- end }}