apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-plugin-daemon
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
spec:
  type: {{ .Values.plugin_daemon.service.type }}
  ports:
    - port: {{ .Values.plugin_daemon.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon 