{{- if .Values.plugin_daemon.enabled }}
{{- if .Values.plugin_daemon.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dify.fullname" . }}-plugin-daemon-pvc
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
spec:
  accessModes:
    - {{ .Values.plugin_daemon.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.plugin_daemon.persistence.size | quote }}
  {{- if .Values.plugin_daemon.persistence.storageClass }}
  storageClassName: {{ .Values.plugin_daemon.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
