---
apiVersion: v1
kind: Service
metadata:
  # dify-api would confict with dify-api program
  # use another name
  name: {{ include "dify.fullname" . }}-api-svc
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-frontend
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- if .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml .Values.frontend.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
spec:
  type: {{ .Values.sandbox.service.type }}
  ports:
    - port: {{ .Values.sandbox.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.fullname" . }}-nginx
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: "10.104.179.207"
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx